# Generated by Django 4.0.6 on 2022-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
