# Generated by Django 4.0.6 on 2022-08-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_resposta_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='texto',
            new_name='texto_pergunta',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='texto',
            new_name='texto_resposta',
        ),
    ]
