# Generated by Django 4.0.6 on 2022-08-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_rename_texto_pergunta_texto_pergunta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='id_pergunta',
            new_name='fk_id_pergunta',
        ),
    ]
