# Generated by Django 4.0.6 on 2022-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_rename_id_pergunta_resposta_fk_id_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='texto_resposta',
            field=models.CharField(max_length=50),
        ),
    ]
