# Generated by Django 4.0.6 on 2022-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_resposta_texto_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto_pergunta',
            field=models.CharField(max_length=200),
        ),
    ]
