# Generated by Django 4.0.6 on 2022-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_pergunta_texto_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='texto_resposta',
            field=models.CharField(max_length=50, verbose_name='Answers'),
        ),
    ]
